language: node_js
node_js:
- stable
before_install:
- npm install -g npm@latest
install:
- npm install
script:
- npm run test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: nJHrEhmrH1ZjDYGo1brB6peReuwypnagBAz99oLP/wwH+H6M87Vg7b5UMzSoAaMvrrnIftAPXv7VWteWTqK8EYbhcaB9SOo5k+1Q9bnoW3VnmJXsVnmX8LyxRAJL+UXWMQQUqqMPlogNhDi6xfVpeBUbmKpEACa7eg82/sX5frmAr9dskaMtxxdq3qR1GxFQi53JxkMjqpqst46igM8tc1SBBy3Up7dgk0H6OB/iXhfBVXSkLJ1UMkhTa6K2MQrHs5xW0zo8ditDkJmlltiVEmUS9mDC4EGpZ17VTypqaom/jbGwtx4uDUpfpuyL49pt6ZLx0YBbWViLxZiSm3+Ru5na5p5+Wp7sXJZbXei4YM85wzknXDfg/penm/4ndh9MyUMKgJwvd8yB9zHPAlv6q/kzn6PYo0h0Q7yX7JXBjgc1sNoKnSgfLKGaYUUGgYyb1wh1tCAdaN32vrebZKoZnGv2KjbB06aBp3lftJUqCmt9ud0u4cBZIr9fp8Es726pdLdUw+3o/WX8s+K6Q4hicV0PO2wpfuXCWmRUXSJ+52d4qYk24wYcYo69QuEypDzirOSBQFGMx/n6JCeZZqBbVqv7BfnLIxb8+n7+DE+72tp60lAtBIszHll/3Fvlbo/rrwTFsasW/KndS5ENoKWfcbSkuxsYf+kQi2lClCa9heE=
  app: gram-gram-gram
  on:
    repo: FayeCarter/instagram
