language: node_js
node_js:
- stable
before_install:
- npm install -g npm@latest
install:
- npm install
script:
- npm run test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: 0eHmACgn+nu09KNPGVNPS5FduyjEAjBX7m/Sdz8dfyiEvs5U0BSTsUM2TbjIWaxo67SrwuT+Q+HSyKH8T5ZLlnbv2sow+xEa8SGQnAX6QxypvWXFY/Xy5s+eLGXqe4KK4W4711vbm/mefBht8hALDJQgQT+H5caQ4k56j2X7Xa1LHyrwjIIrY/uyCvczWVlrmk99S2jBBN2XBH4BpiZ4KvJzaeI2qkukK4ZFWWXIJ1Mm3fQyyhy36tnd/RPL7V0mjpy0LCRO7jRT7s+wNFz1MKRJt10VprLCDJ68H4uHMxNqqGzSF6ZjqQFGwBmN4FnoLITb2sr6pVxw1QUq9C6M/5B8SQJlTe6MCF96UcavjK0nyfbt0PACaf7grCDE67TCAM2BlKJZNdVXfhN4n3JgvK4NOkinmONLQRIX2ClXCG0LJz/CK18KfL2Eaf9OkLCxu2FrI3xfJHDq93vGpaJt8Uiu0Xp/y6VUc5ntgBLBmw8IdfIXjtWP/puOmpdwyWRBF4leV+CDfIDojFRMIApg5r5duj3PtvmWdWTxRiWVnDDJ9+1ttMgrUGSib0xCjhZuSifxu8zREyt7BKMDvZ0SQs1eksVubxB0UWDiedmYzcYrNjBS3vKzRdASUIgotnhnr0USICKKrcWbNX+wKg0fI1MM8cD479Cm1F5YCS5vqSA=
