language: node_js
node_js:
- stable
before_install:
- npm install -g npm@latest
install:
- npm install
script:
- npm run test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: EqQO7j6HgXqs51oiIBoDt82jWQuBBGbzPVs+B15jimvSuG+fWoRsy6+YCZEJYlkN3do8AxyHanJyXXPZsRtuBKYTn/uETxMKM24T9WFJ3HE7VU3X/gozG8AjE1NvHsFNkS6Ak6Gr2a8tRUbHwSoJ7fIaCyE3CKumTzedQoioOSOzstD2EtLyAwPoXsXeBnsiR6YOn5igtYDuZBG536fnK/vn8n/nyIFfTTpytqppz2HLe/vcUhrlSi63b+7mhme/Qyq/jzPeAynM3IvHptdn7yL8gDWnbtxR3Z61KDwCoKf9uVkKItU5F0oSBEk5JJJaHnwcL7fW0+5SLmkehzLWptg2exz/VcUanseIx+w0ew82NnivbC5moBd+/+InPqy3T+9MqhyUnLHUcm2yz3Thq2/2mi4gi1+uOtmjV9O1nFQjP6ubNe07Xbht6myd8QV1WGTEz+gEWYjGQMq/uYDsY87oaWLYo+zffqbkd2DzWKprQC/x8mLRgJ5aNm9kwiRe+tw7kmT6IFuUa0zlV2WCc2YjIhpdSGLqDtVPRJJ8+vHjeV0m8ufMRCrs3bcZcp+IdwtUPV1cUZIc9vCkZbFDsNyWfxlj5UI8sohQKjvXxzsY6Nt8Gj+pLxfDJVIj2Uf6/CFmPqXUfP+gWUPpkwmccq+CMQ/jbSOyqIUz8+6m/qI=
  app: gram-gram-gram
  on:
    repo: FayeCarter/instagram
