language: node_js
node_js:
- stable
before_install:
- npm install -g npm@latest
install:
- npm install
script:
- npm run test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: M+ztGU9d6P1IBV5jLmD6c1nge/eHERqy0z1vHJhfS4r1pqsJMEhEc7dnG7ULsxexbGS4pZtQyICocZe3JfD+Ml1jLRkH5CCPny1SKIQ+u1lsQC8x6rJQNL/73+LvqTUDoUA2ddqM7iFRXvP9e16hxKz4+4C9gjFHuDYOESiOfDAS873uB+zG4hLvCD+PyalnKjnuRfBRfaDWCw8/ajsOjZgW+xzR3i/3oPBf4jimfuwNZ80KjmbvrtVNmZAqhmZ8aYUq5PWJRVgovxVhmAa9BytYGDqmPfF4J+LcilkF+sQbSApVy4STZp7oco5wGSVeQLWSSVHa+coknSxjsaRBg3ckG0Mt204gNRg5QU2+wTzAd3NgmO9KhMHyd3Lj7+MQL7x1sP1V+52pyormQu3QJXnN66qMxvUUUtPbhjdJLwVzYroWx5AwvXxUNyxpvWB0BRk+srFYSIHY4x0KNUIqlf0CnqlY23tgWc+Mqk5yGw94oqgNhiDHmVncPpb0WyewRQY4gG2ao+5AESj8YdqCpNhlakkHWN1w4BxiwsM5DGpBKj1nlE6Zay2LZRaMp+s7ZF2+aBqfNCrcG8lpgg0ofVBjnA9C7wlSKaoKT2xl9VfIUjnk3cHJ9GkIyM+tHPkyLO11KJBTDf8KQ75UNp7m7Vnr0n95cJ8SgpiEVnY8iSE=
