language: node_js
node_js:
- stable
before_install:
- npm install -g npm@latest
install:
- npm install
script:
- npm run test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: xTpOxCVOPOV0kBsBmZhEfsaVg/VpDf+TvW3qxaTrzQbS1na6tLej14DPIU1kF28N/2yb3K7WMEc3+uVA/mDDxqnkwYFnVVtavuCJOQT/oXTLsp/myjj0YQ4mwDJy5vwMxLMipU+E1tlMu6M9aPNKGTAA7KFGbDkadf984tuGmejPv9x1cwxOZTDaBdIqxDxUP86sQo/QFTy4xitEg1svPlG3dxNhnC0oiveUkC4vVvoFgWUJTsL31mffboi/c1xBYwKxtuwM5AYZUqQWqMINEOgr3gw3OhoMOWqIt6IFgaOG5UsxWAlX2b2lKxOF8WxalIZeW4HHQXQUdjZzGr64rANJsQ2/EQBUgkwNZXY1+Uaw7zVECmH1tEFYLACOvEVZmPd1Pd8KvlaOZJVG8tgOOWDVup593XxV60POzKvNMx+IHFZsZ4GE5ckZw4gj8xt4JpWjtmPMTM3jnog1yhyaHw7nt+iEaBWNqhXEyhKCCpDXKsoWyQTwPvu/ICjPLw54nPOMZ2UGHXtxk/Ji/HztH7beRcS4gUDP8wVJj6vwFNlfv+ZLT/pyU3c80j38IM3B6PxZz0q9CoRJh38kVtKq9QRd0nVhXb7iLdg7G1lDgMeVzvIspev58+bBTQVunh/jxs4y26vLRhHWKZ9bfINLJ5+luFkkrUNUipAX2Jm4aoA=
